### ISSUE TITLE
Support for Istio v1.0.0

### ISSUE THREAD

**Issue by boazjohn** [nmnellis/vistio#10]
Hi,

I was trying vistio out, but it doesn't work with the new istio release (v1.0.0) as the data-points have changed a bit. 
I guess there are also a set of new grafana dashboards with the queries that has been used. How can I fix this?

Ref: https://github.com/istio/istio/tree/405f47f54d19e6d998aa3e863ec9e2bc23c157f1/addons/grafana/dashboards

**Comment by nmnellis** [comment]
Yeah I am actively working on this and should have an update soon, in the mean time here are the queries you should use
global level - w/ Istio-ingressgateway
```
sum(rate(istio_requests_total{reporter="source", source_workload="istio-ingressgateway"}[1m])) by (response_code)
```

global level - no Istio-ingressgateway
```
sum(rate(istio_requests_total[1m])) by (response_code)
```

cluster level
```
sum(rate(istio_requests_total[1m])) by (source_app,destination_service,response_code)
```

**Comment by rootsongjc** [comment]
@nmnellis that didn't solve all the problems. When I change the queries, it works for the global view, but when I go into `global/istio-mesh` there is no data, 0 services.

**Comment by nmnellis** [comment]
you also need to update your source to now be `source_app`

https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/blob/9ba07e1479e0a9b949d364e8efe058dd41a4575a/addon/vistio/vistio-mesh-only.yaml#L28

**Comment by rootsongjc** [comment]
@nmellis thanks, it works for me.

**Comment by waytoharish** [comment]
Hi As discussed my service is running on NodePort as i don't have any external loadBalancer but web still trying to access on localhost

**Comment by waytoharish** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9091/graph?offset=0. (Reason: CORS request did not succeed)

**Comment by killcity** [comment]
any progress on this one?

**Comment by nmnellis** [comment]
Are you referring to 1.0 support or CORS?

**Comment by killcity** [comment]
Oh sorry, 1.0 support. Is it just the above tweaks to the manifest? Thanks for all the work on this!

**Comment by nmnellis** [comment]
yeah the above queries should work for 1.0, ive just been lazy. ill make some new values files now

**Comment by killcity** [comment]
@nmnellis No worries! Is there anything else different regarding compat with Istio 1.0? Do we need to supply our own `promviz` server? I skipped using the port-forward in lieu of just modding `UPDATE_URL` to `http://vistio-api.vistio:9091/graph`, just not sure what to do with `--config.promviz-reload-url`. I had pointed it to the same url as above, but no dice.

Thanks!

**Comment by nmnellis** [comment]
Closing this as I now added the metrics to the default helm install. https://github.com/nmnellis/vistio/pull/13
