### ISSUE TITLE
Installing Vistio on Linux/Windows

### ISSUE THREAD

**Issue by muralikanagala** [nmnellis/vistio#12]
Hi there - We are using Prometheus in a non-container infrastructure and looking to visualize our network activity using Vistio.  Is there any documentation on how to install Vistio on a Linux/Windows machines? or on how to build a binary using the source code?

**Comment by nmnellis** [comment]
This shouldn't be too hard, you can either install docker on your vm instances and pull the docker containers. Or refer to how the docker containers in the api and web and see how the projects are being built.
